name: IA Code Review Reusable

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  workflow_call:
    secrets:
      AI_PR_GITHUB_TOKEN:
        required: true

jobs:
  Review-Amazon-Bedrock:
    concurrency:
      group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-ia-code-review
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::285724677469:role/GHA-ROLE-STACK-GitHubActionsServiceRole-wG9XBUbwU1YC"
          role-session-name: gha-session
          aws-region: us-east-1

      - name: PR review
        uses: tmokmss/bedrock-pr-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.AI_PR_GITHUB_TOKEN }}
        with:
          debug: ${{ vars.AI_PR_DEBUG }}
          review_simple_changes: ${{ vars.AI_PR_REVIEW_SIMPLE_CHANGES }}
          review_comment_lgtm: ${{ vars.AI_PR_REVIEW_COMMENT_LGTM }}
          bedrock_model_temperature: ${{ vars.AI_PR_BEDROCK_MODEL_TEMPERATURE }}
          bedrock_heavy_model: ${{ vars.AI_PR_BEDROCK_MODEL }}
          bedrock_light_model: ${{ vars.AI_PR_BEDROCK_MODEL }}
          bedrock_retries: 10
          language: pt-BR
          system_message: ${{ vars.AI_PR_SYSTEM_MESSAGE }}
          summarize: ${{ vars.AI_PR_SUMMARIZE_MESSAGE }}
